### ISSUE TITLE
Questions about testing

### ISSUE THREAD

**Issue by engqing** [omniobject3d/OmniObject3D#12]
Hello, track 1 model tuning seems to be in a specific category, does this mean that there will be many fine-tuned models, how to test on the hidden test set? I look forward to hearing from you

**Comment by wutong16** [comment]
Hi! We encourage participants to explore category-agnostic methods instead of methods that fine-tune one model per category. A unified model that applies to arbitrary categories is more practical in real-world applications.

**Comment by engqing** [comment]
Does that mean that fine-tuning the model is basically unnecessary?

**Comment by wutong16** [comment]
It depends. For object-level fine-tuning, you can design adaptive modules that fine-tunes on the given views of the test object, as long as the computational cost is acceptable. Additionally, if needed, you can incorporate prior knowledge from other foundational models.

For category-level fine-tuning, it may not be feasible since users cannot assume the availability of a supportive category-level dataset for every new object they encounter in real-world situations.

**Comment by engqing** [comment]
Ok, thank you for your reply.

**Comment by engqing** [comment]
This error occurred when I used pixelnerf to test on the hidden test set. I didn't change the test code. Can you help me?
![image](https://github.com/omniobject3d/OmniObject3D/assets/115127943/52ded70e-57a4-42d7-875a-ef2dfc05dd5d)

**Comment by fuxiao0719** [comment]
Hi, the issue has been resolved in the latest release. We modified the default source view number from 3 to 1,2,3 and inadvertently missed updating the latest information. Apologies for the oversight.
