### ISSUE TITLE
When will the captions be available?

### ISSUE THREAD

**Issue by akanimax** [omniobject3d/OmniObject3D#22]
Hello! 
Thanks a lot for releasing this cool dataset. This benchmark will be very useful for the research community. 

As mentioned in your ICCV 2023 talk regarding the newly obtained captions for the 3D scans, could you please comment on when those captions will be available? 
Else, it would be super helpful if you could point me to the pipeline that can be used for generating captions. 

Cheers!
@akanimax

**Comment by omniobject3d** [comment]
Hi! The caption is available [here](https://drive.google.com/file/d/1R-kC3EdMZmwyaX0EkU7CvZK8VSVRPMaS/view), sharing the same object IDs with the other modalities.

The caption we are releasing is annotated and verified by **human experts**, which we have found to be **more accurate and comprehensive** than the automatic way for generating captions, at least for now. As for the automatic pipeline, please refer to [Cap3D](https://github.com/crockwell/Cap3D) if you are interested! We are using a similar way as they do, but we are not releasing the generated captions currently due to their lower quality than human annotations.

**Comment by buaacyw** [comment]
Thanks for your work! But I still can't download the caption from your link. Are there any problems?

**Comment by akanimax** [comment]
Awesome! The captions look good. Thanks 👍.

**Comment by akanimax** [comment]
Some of the sequences are missing captions. These are the sequences from my experiments:

```
book_023
chocolates_011
chocolates_002
chocolates_008
chocolates_016
chocolates_012
chocolates_001
chocolates_006
chocolates_015
chocolates_017
chocolates_004
chocolates_009
chocolates_003
chocolates_010
chocolates_014
chocolates_013
joystick_001
phone_shell_001
sequence thermometer_001
```
