### ISSUE TITLE
download link on google cloud

### ISSUE THREAD

**Issue by florinshen** [omniobject3d/OmniObject3D#23]
hi, may i ask will you provide the dataset download link on google cloud ? The current download link on openxlab is quite unstable and the api of openxlab-cli is changed.

**Comment by wutong16** [comment]
Thank you for your feedback! We are working on this and will maintain a download link on Google Drive soon. I'll pin you when we successfully upload the Google Drive version.

**Comment by florinshen** [comment]
Thank you for your quick reply. Another issue i encountered is that there are only 5509 instance captured in the blender_render directory, the number of instance in some category is even less than 10, like antique. Is the current data stored in openxlab missing some parts ?

**Comment by omniobject3d** [comment]
There should be 5,913 instances available online, excluding the [hidden test set](https://drive.google.com/file/d/1GKEa-r1__tnVKAZSF5I5uWcLh1cAllqh/view?usp=drive_link) that was utilized for our ICCV challenge over the past few months. The data currently stored in OpenDataLab may be incomplete due to missing portions or potential package loss during the download process. 

Nevertheless, it is normal to have less than 10 instances for some rare classes, as the dataset exhibits a long-tailed distribution of objects.

We are presently in the process of uploading the dataset to Google Drive, and please be patient since it might take some time due to network limitations.

**Comment by florinshen** [comment]
ok, fine. thank u.

**Comment by wutong16** [comment]
Hi, we have successfully resolved the issue with our data platform. Additionally, we have provided an alternative option for downloading the data via Google Drive. You can access the download link [here](https://drive.google.com/drive/folders/1-hlkTqUJR_J2xht1qztmX2xAq_qNw4vn?usp=sharing). 

If you encounter any further difficulties or have any questions related to data downloading, please don't hesitate to reach out to us.

**Comment by florinshen** [comment]
thanks a lot. Close since issue has resolved.
