### ISSUE TITLE
The raw-scans folder only contain 110 items

### ISSUE THREAD

**Issue by shangbuhuan13** [omniobject3d/OmniObject3D#24]
Thanks for your great dataset. 
After downloading the dataset, I noticed that "raw scans" only have 110 classes, while "point cloud" has 216 classes.  I am a little confused. Did I download the dataset correctly? Or the data of remaining classes is still under construction?

Thank you very much!

**Comment by wutong16** [comment]
Sorry for any confusion. Most recently, we have observed that the data stored on the current server became incomplete, possibly due to missing segments or package losses during the download process. We are actively addressing this issue and working to resolve it. Simultaneously, we are in the process of uploading the dataset to Google Drive as a backup. 

Kindly exercise patience, and I will keep you updated as soon as the problem is rectified.

**Comment by shangbuhuan13** [comment]
Thank you very much for the reply!

**Comment by wutong16** [comment]
Hi, we have successfully resolved the issue with our data platform. Additionally, we have provided an alternative option for downloading the data via Google Drive. You can access the download link [here](https://drive.google.com/drive/folders/1-hlkTqUJR_J2xht1qztmX2xAq_qNw4vn?usp=sharing). 

If you encounter any further difficulties or have any questions related to data downloading, please don't hesitate to reach out to us.
