### ISSUE TITLE
Alignment between raw_scans and blender_renders for surface reconstruction from images

### ISSUE THREAD

**Issue by Szy-Young** [omniobject3d/OmniObject3D#47]
Hi @wutong16 @fuxiao0719 @omniobject3d, first very thanks for sharing such a great dataset to the community! 

Currently I am trying to apply this dataset for surface reconstruction. To my understanding, I should try to use images in `blender_renders` or `blender_renders_24_views` to fit a surface, and compare it with the GT mesh in `raw_scans`. However I find these images and meshes seem to lie in different coordinates (visualized below, red cameras from `blender_renders`, green cameras from `blender_renders_24_views`; The scene is `garage_kit_014`).
![image](https://github.com/user-attachments/assets/1a28d27c-404e-4543-891c-847a3edf29f4)
![image](https://github.com/user-attachments/assets/213bc5d2-da08-413c-a589-ce37f538a5a3)

Could you kindly help me make clear how to align the coordinates of multi-view images and the surface meshes? Many thanks for your time!

**Comment by wutong16** [comment]
Hi @Szy-Young, thank you for your interest in our work. To align the coordinate of multi-view images from `blender_renders` to `raw_scans`, you can refer to the evaluation tool [here](https://github.com/omniobject3d/OmniObject3D/blob/main/tools/mesh_eval.py#L119), where we use the stored `scale` factor to do the alignment. For `blender_renders_24_views`, which is rendered using a similar way of GET3D, we cannot fully assure the alignment, since these files are mainly used for GET3D-like data loaders.

**Comment by Szy-Young** [comment]
@wutong16 Very thanks for your kind and helpful explanation!
